### ISSUE TITLE
Compatible with 1.8.1 ?

### ISSUE THREAD

**Issue by billymedia** [mwbrooks/cordova-plugin-menu#38]
Is this compatible with PG 1.8.1 ? Getting lots of errors. assuming its not.

**Comment by mwbrooks** [comment]
Unfortunately it's not. I haven't had the opportunity to update this since 1.0.0.

We (Apache Cordova) are currently formalizing the plugin specification and this plugin has been proposed as a good use case, so I'll be leveraging that reason as an opportunity to refactor this plugin. Aside from the plugin interface, I think the entire plugin design can use a good rethink.

**Comment by billymedia** [comment]
Are u aware of any android plugins that I could use as an alternative?

**Comment by mwbrooks** [comment]
Hey, I know Alex Michel has an [Android menu plugin](https://github.com/amichel/phonegap-plugins/tree/master/Android/MenuPlugin). Although I haven't personally used it, he contacted me about possibly merging it into cordova-plugin-menu. I'm all for this, but unfortunately I've been to busy to reply... which I'll do right now :)

Any feedback on his plugin would be great! I also can put the two of you in contact if you'd like.

**Comment by mtamony** [comment]
Does your plugin make use of iOS automatically adding the More Tab when there are more than five Tabs on iPhone?
